#H2 Database Credentials
H2_DB_URL=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

H2_DB_USERNAME=ebest

H2_DB_PASSWORD=e6e5t


DB_URL=jdbc:mysql://localhost:3306/afiapass_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
DB_USERNAME=root
DB_PASSWORD=root

# Mail credentials
MAIL_USERNAME=johdani@gmail.com
MAIL_PASSWORD=kdsgmniuxcuoobgd

# JWT credentials
JWT_SECRET_KEY=G++LFCLNKMe/MqiubzY+Y99BYkQ65G8WgLg+5SO5p7M=